INSERT INTO BOOKS (BOOKID,BOOKNAME,AUTHORNAME,ISBN) VALUES (1,'MICROSERVICES','ISHRAT',1234);
INSERT INTO BOOKS (BOOKID,BOOKNAME,AUTHORNAME,ISBN) VALUES (2,'GO-LANG','VENKAT',1235);
INSERT INTO BOOKS_CHAPTERS (BOOK_CHAPTER_ID , CHAPTER_TITLE,CHAPTER_SUMMARY,CHAPTER_PAGES,BOOKID) VALUES(1,'MICROSERVICES INTRO','THIS IS INTRODUCTION ABOUT MICROSERVICES',2,1);
INSERT INTO BOOKS_CHAPTERS (BOOK_CHAPTER_ID , CHAPTER_TITLE,CHAPTER_SUMMARY,CHAPTER_PAGES,BOOKID) VALUES(2,'MICROSERVICES FEATURES','THIS IS FEATURES ABOUT MICROSERVICES',12,1);
INSERT INTO BOOKS_CHAPTERS (BOOK_CHAPTER_ID , CHAPTER_TITLE,CHAPTER_SUMMARY,CHAPTER_PAGES,BOOKID) VALUES(3,'GO-LANG INTRO','THIS IS INTRODUCTION ABOUT GO-LANG',3,2);
INSERT INTO BOOKS_CHAPTERS (BOOK_CHAPTER_ID , CHAPTER_TITLE,CHAPTER_SUMMARY,CHAPTER_PAGES,BOOKID) VALUES(4,'GO-LANG FEATURES','THIS IS FEATURES ABOUT GO-LANG',5,2);